
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.DrawingArea drawingarea1;

	private global::Gtk.DrawingArea drawingarea2;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.Image image3;

	private global::Gtk.TextView textview4;

	private global::Gtk.Label label3;

	private global::Gtk.Table table3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Entry login;

	private global::Gtk.Entry password;

	private global::Gtk.Label error_message;

	private global::Gtk.Button button1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.Name = "drawingarea1";
		this.fixed3.Add (this.drawingarea1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.drawingarea1]));
		w1.X = 592;
		w1.Y = 88;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.drawingarea2 = new global::Gtk.DrawingArea ();
		this.drawingarea2.Name = "drawingarea2";
		this.fixed3.Add (this.drawingarea2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.drawingarea2]));
		w2.X = 510;
		w2.Y = 115;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.fixed3.Add (this.fixed2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.fixed2]));
		w3.X = 456;
		w3.Y = 300;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.image3 = new global::Gtk.Image ();
		this.image3.Name = "image3";
		this.image3.Xalign = 1f;
		this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("HumanRightsTracker.images.logo.jpg");
		this.fixed3.Add (this.image3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.image3]));
		w4.X = 37;
		w4.Y = 37;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.textview4 = new global::Gtk.TextView ();
		this.textview4.Buffer.Text = "\nSistema de Monitoreo de Derechos Humanos\n\nCopyright 2011 @ i(dh)eas \n";
		this.textview4.CanFocus = true;
		this.textview4.Name = "textview4";
		this.textview4.Editable = false;
		this.textview4.CursorVisible = false;
		this.textview4.LeftMargin = 7;
		this.textview4.RightMargin = 7;
		this.textview4.Indent = 4;
		this.fixed3.Add (this.textview4);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.textview4]));
		w5.X = 42;
		w5.Y = 261;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Human Rights Tracker");
		this.fixed3.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
		w6.X = 84;
		w6.Y = 17;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		this.table3.BorderWidth = ((uint)(12));
		// Container child table3.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("User");
		this.label4.Justify = ((global::Gtk.Justification)(3));
		this.table3.Add (this.label4);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.label4]));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.table3.Add (this.label5);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.label5]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.login = new global::Gtk.Entry ();
		this.login.CanFocus = true;
		this.login.Name = "login";
		this.login.IsEditable = true;
		this.login.InvisibleChar = '●';
		this.table3.Add (this.login);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.login]));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.password = new global::Gtk.Entry ();
		this.password.CanFocus = true;
		this.password.Name = "password";
		this.password.IsEditable = true;
		this.password.Visibility = false;
		this.password.InvisibleChar = '●';
		this.table3.Add (this.password);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.password]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(0));
		this.fixed3.Add (this.table3);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.table3]));
		w11.X = 282;
		w11.Y = 68;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.error_message = new global::Gtk.Label ();
		this.error_message.Name = "error_message";
		this.error_message.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
		this.fixed3.Add (this.error_message);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.error_message]));
		w12.X = 393;
		w12.Y = 36;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Login");
		this.fixed3.Add (this.button1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button1]));
		w13.X = 468;
		w13.Y = 145;
		this.Add (this.fixed3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 598;
		this.DefaultHeight = 392;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.authenticate);
	}
}
